const countryCurrencies = {
    "afghanistan": "AFN",
    "albania": "ALL",
    "algeria": "DZD",
    "andorra": "EUR",
    "angola": "AOA",
    "argentina": "ARS",
    "armenia": "AMD",
    "australia": "AUD",
    "austria": "EUR",
    "azerbaijan": "AZN",
    "bahamas": "BSD",
    "bahrain": "BHD",
    "bangladesh": "BDT",
    "barbados": "BBD",
    "belarus": "BYN",
    "belgium": "EUR",
    "belize": "BZD",
    "benin": "XOF",
    "bhutan": "BTN",
    "bolivia": "BOB",
    "bosnia and herzegovina": "BAM",
    "botswana": "BWP",
    "brazil": "BRL",
    "brunei": "BND",
    "bulgaria": "BGN",
    "burkina faso": "XOF",
    "burundi": "BIF",
    "cabo verde": "CVE",
    "cambodia": "KHR",
    "cameroon": "XAF",
    "canada": "CAD",
    "central african republic": "XAF",
    "chad": "XAF",
    "chile": "CLP",
    "china": "CNY",
    "colombia": "COP",
    "comoros": "KMF",
    "congo (congo-brazzaville)": "XAF",
    "costa rica": "CRC",
    "croatia": "HRK",
    "cuba": "CUP",
    "cyprus": "EUR",
    "czechia (czech republic)": "CZK",
    "denmark": "DKK",
    "djibouti": "DJF",
    "dominica": "XCD",
    "dominican republic": "DOP",
    "ecuador": "USD",
    "egypt": "EGP",
    "el salvador": "USD",
    "equatorial guinea": "XAF",
    "eritrea": "ERN",
    "estonia": "EUR",
    "eswatini (fmr. swaziland)": "SZL",
    "ethiopia": "ETB",
    "fiji": "FJD",
    "finland": "EUR",
    "france": "EUR",
    "gabon": "XAF",
    "gambia": "GMD",
    "georgia": "GEL",
    "germany": "EUR",
    "ghana": "GHS",
    "greece": "EUR",
    "grenada": "XCD",
    "guatemala": "GTQ",
    "guinea": "GNF",
    "guinea-bissau": "XOF",
    "guyana": "GYD",
    "haiti": "HTG",
    "honduras": "HNL",
    "hungary": "HUF",
    "iceland": "ISK",
    "india": "INR",
    "indonesia": "IDR",
    "iran": "IRR",
    "iraq": "IQD",
    "ireland": "EUR",
    "israel": "ILS",
    "italy": "EUR",
    "jamaica": "JMD",
    "japan": "JPY",
    "jordan": "JOD",
    "kazakhstan": "KZT",
    "kenya": "KES",
    "kiribati": "AUD",
    "kuwait": "KWD",
    "kyrgyzstan": "KGS",
    "laos": "LAK",
    "latvia": "EUR",
    "lebanon": "LBP",
    "lesotho": "LSL",
    "liberia": "LRD",
    "libya": "LYD",
    "liechtenstein": "CHF",
    "lithuania": "EUR",
    "luxembourg": "EUR",
    "madagascar": "MGA",
    "malawi": "MWK",
    "malaysia": "MYR",
    "maldives": "MVR",
    "mali": "XOF",
    "malta": "EUR",
    "marshall islands": "USD",
    "mauritania": "MRU",
    "mauritius": "MUR",
    "mexico": "MXN",
    "micronesia": "USD",
    "moldova": "MDL",
    "monaco": "EUR",
    "mongolia": "MNT",
    "montenegro": "EUR",
    "morocco": "MAD",
    "mozambique": "MZN",
    "myanmar (formerly burma)": "MMK",
    "namibia": "NAD",
    "nauru": "AUD",
    "nepal": "NPR",
    "netherlands": "EUR",
    "new zealand": "NZD",
    "nicaragua": "NIO",
    "niger": "XOF",
    "nigeria": "NGN",
    "north korea": "KPW",
    "north macedonia (formerly macedonia)": "MKD",
    "norway": "NOK",
    "oman": "OMR",
    "pakistan": "PKR",
    "palau": "USD",
    "palestine state": "ILS",
    "panama": "PAB",
    "papua new guinea": "PGK",
    "paraguay": "PYG",
    "peru": "PEN",
    "philippines": "PHP",
    "poland": "PLN",
    "portugal": "EUR",
    "qatar": "QAR",
    "romania": "RON",
    "russia": "RUB",
    "rwanda": "RWF",
    "saint kitts and nevis": "XCD",
    "saint lucia": "XCD",
    "saint vincent and the grenadines": "XCD",
    "samoa": "WST",
    "san marino": "EUR",
    "sao tome and principe": "STN",
    "saudi arabia": "SAR",
    "senegal": "XOF",
    "serbia": "RSD",
    "seychelles": "SCR",
    "sierra leone": "SLL",
    "singapore": "SGD",
    "slovakia": "EUR",
    "slovenia": "EUR",
    "solomon islands": "SBD",
    "somalia": "SOS",
    "south africa": "ZAR",
    "south korea": "KRW",
    "south sudan": "SSP",
    "spain": "EUR",
    "sri lanka": "LKR",
    "sudan": "SDG",
    "suriname": "SRD",
    "sweden": "SEK",
    "switzerland": "CHF",
    "syria": "SYP",
    "taiwan": "TWD",
    "tajikistan": "TJS",
    "tanzania": "TZS",
    "thailand": "THB",
    "timor-leste": "USD",
    "togo": "XOF",
    "tonga": "TOP",
    "trinidad and tobago": "TTD",
    "tunisia": "TND",
    "turkey": "TRY",
    "turkmenistan": "TMT",
    "tuvalu": "AUD",
    "uganda": "UGX",
    "ukraine": "UAH",
    "united arab emirates": "AED",
    "united kingdom": "GBP",
    "united states": "USD",
    "uruguay": "UYU",
    "uzbekistan": "UZS",
    "vanuatu": "VUV",
    "vatican city (holy see)": "EUR",
    "venezuela": "VES",
    "vietnam": "VND",
    "yemen": "YER",
    "zambia": "ZMW",
    "zimbabwe": "ZWL"
  };
const submitbutton=document.getElementById("submit");
 submitbutton.addEventListener("click",updateForm)
 function makeUrl(tocountry,fromCountry)
 {
    let to_currency="";
    let base_currency="";
    for(i in countryCurrencies)
        {
            if(i==tocountry)
                {
                   
                  to_currency=countryCurrencies[i];
                }
                if(i==fromCountry)
                    {
                        
                        base_currency=countryCurrencies[i];
                    }
        }

   let url=`https://api.freecurrencyapi.com/v1/latest?apikey=fca_live_2rXBUpvfhMDHhl7aSCaUTfdXftQS9zd6V1xCD9e2&currencies=${to_currency}&base_currency=${base_currency}`;
   console.log(url);
   return url;
 }
 async function updateForm()
 {
  event.preventDefault();
  let fromCountry=(document.getElementById("fromCountry").value).toLowerCase();
  let toCountry=(document.getElementById("toCountry").value).toLowerCase();
  let amount=(document.getElementById("amount").value);
  console.log(amount);
  let result=document.getElementById("result");
  const url=makeUrl(toCountry,fromCountry);
  let data= await fetch(url);
  let parsed = await data.json();
    let key = Object.keys(parsed["data"])[0];
    let exchangeRate = parsed["data"][key];
    let convertedAmount = amount * exchangeRate;
 result.innerText=convertedAmount;
 }
